### PR TITLE
Improved error handling

### LINKED ISSUE #13: Clean up errors
## Current state of this issue

There are a significant number of `ProviderIssue` type errors that do not give the end user any information and requires that they look at the log to determine what went wrong. Trying to include either `#[cause] Box<failure::Fail>` or `#[cause] failure::Error` do not work without additional infrastructure [[1]](https://github.com/adeschamps/lcm-rust/pull/33#issuecomment-369114919). Using `#[cause] failure::Compat<failure::Error>` will compile but will not work as expected [[2]](https://github.com/adeschamps/lcm-rust/pull/33#issuecomment-369362884).

An [Error and ErrorKind pair](https://boats.gitlab.io/failure/error-errorkind.html) has been suggested but the current plan is to wait until this library has been used some and until `failure` hits 1.0 [[3]](https://github.com/adeschamps/lcm-rust/pull/33#issuecomment-369462132).

## Original Post

Right now, the error situation is a bit of a mess. This is my first time using `failure` and I haphazardly added error types as I went. This definitely needs to be cleaned up to provide a more informative and usable interface.

At the very least, I think the `Lcm` methods should all return a single error. What this error would look like, I don't know. But the major problem right now is that having them all return different types makes using them together painful without using the `failure::Error` type (which is not an ideal type to use).

In other words, the bare minimum is that we need to find an error type `T` such that the following code compiles:
```rust
fn do_stuff() -> Result<(), T> {
    let mut lcm = Lcm::new()?;
    let sub = lcm.subscribe("TEST", |m: Foo| { .. })?;
    lcm.publish("OTHER TEST", m)?;

    lcm.handle()?;
    Ok(())
}
```

### PR DESCRIPTION
**Pull request by neachdainn**
This solves the error mess in three ways:
1. There is now an `Error` type that has variants for the four major error types. Any situation where the user wants to return errors from any combination of LCM operations can just return this type. If the user wants to try and recover from the error, they still have enough information to make this possible.
2. Provider specific errors have been conglomerated into `ProviderIssue` variants. At some point, I want these to include a `#[cause]` of some sort but I'm not sure what way is best. See followup comments for more info.
3. The `impl From<T>` items are hidden from docs. This isn't perfect but I am of the opinion that undocumented things can be changed without being considered breaking, so this is fine for now. Again, see followup comments for more info.

### CODE REVIEW

**Comment by neachdainn** [comment]
There are the issues that I thought about while writing these changes. I would like them to be resolved in some way before this is merged (assuming these changes are acceptable):

1. We should make the `From<T>` implementations for all of these errors unavailable to the end user. Most of them only exist to make the code more readable in this crate (via the `?` operator) and probably shouldn't be used by the end user. The best method for doing this (that I've heard) is to create separate "internal" and "external" errors and only do the `From` implementations for the inner. Until that is done, I have hidden the trait implementations from the docs. As they are hidden from the docs, I don't think I would consider making this change to *not* be a breaking change.
2. There are a lot of `ProviderIssue` type errors in this module. I want to come up with some way to report the errors other than telling the user to look at the log but I'm not sure how to do it. I inintially attempted to use `Box<Fail>` but it didn't work. I think the only options might be:
    1. Use `fail::Error`
        * This is super expensive
        * But it's also not on a happy path
    2. Make this module aware of provider specific errors
        * This could lead to a large number of error types
        * But those could be filtered out via feature flags
        * ...but that could make maintaining projects difficult. I would like to keep backend-specific code away from the end user.

I also would like `lcm::error::Error` to be documented as `lcm::Error`, but that may be something to deal with in #24. I have tried both `#[doc(hidden)]` and `#[doc(no_inline)]` and neither of them gave me the results I wanted. Perhaps actually moving the struct is the only way to do this but that isn't ideal.

**Comment by neachdainn** [comment]
This is also not well tested. I would like to get #32 and #22  fixed soon so we can write tests similar to the ones that the C version of LCM has.

**Comment by adeschamps** [comment]
I think hiding the `From<T>` impls is a fine way to address the first issue. I also wouldn't consider modifications here to be breaking changes in any practical way (every formal definition of "breaking change" has edge cases, as far as I'm aware).

As to the second point, one option is of course to use a boxed error or the `failure::Error` type as one of the variants. Another option is to allow provider-specific error variants. I lean towards the former.

Even though there are still things left to do, I'm inclined to merge this, since it is in a pretty reasonable state.

**Comment by neachdainn** [comment]
I'll fix the conflicts and add the code for the `failure::Error` sometime tonight or tomorrow.

**Comment by neachdainn** [comment]
I have the following issue when trying to use `#[cause] Box<failure::Fail>`: 
`` `failure::Fail + 'static` does not have a constant size known at compile-time ``'

And when I try to use `#[cause] failure::Error`:
`` the trait `std::error::Error` is not implemented for `failure::Fail + 'static` ``


I'm not sure how to solve either of those but I'm going to try and get it figured out tomorrow.

**Comment by adeschamps** [comment]
This may be a use case for defining an [Error and ErrorKind pair][failure].

[failure]: https://boats.gitlab.io/failure/error-errorkind.html

**Comment by neachdainn** [comment]
To replace the current `ProviderIssue` or to replace all of the errors? This is definitely a use case for the pattern.

**Comment by adeschamps** [comment]
It looks like this is a similar situation: https://github.com/withoutboats/failure/issues/176

If you use `ProviderIssue(#[cause] failure::Compat<failure::Error>)` then it'll compile. From that issue it sounds like it doesn't get displayed quite the way you would expect.

I think I'd go this route because it gets us the representation we want. `failure` is releasing 1.0 in a few weesk, so maybe we should just watch that issue. We can manually implement `Fail` if we need to.

**Comment by neachdainn** [comment]
I think the best course of action might be to merge this pull request but not close the issue. We can revisit it after (1) the library has been used enough to learn what kind of error handling would be the most useful and ergonomic and (2) once `failure` hits 1.0.

**Comment by adeschamps** [comment]
Indeed. This looks good to me, but I agree - it has to actually be used.

**Pull request merged**
