### PR TITLE
Add `publish_raw` and `subscribe_raw` methods

### LINKED ISSUE #23: Allow the user to subscribe to a channel using raw message bytes
I have two primary motivations for wanting to do this:
1. It will make it easier to test against the C LCM tests.
2. If there's ever a situation where one wants to get every message from every channel (e.g., a logger), they would need to be able to do it without have a message definition.

I think there are two ways we could do this. The first would be to add some kind of `Lcm::subscribe_raw` function, and the other would be to implement `Message` and `Marshall` for `&[u8]`. I think the former would be the clearest to the user but the latter fits into the existing code more elegantly .

### PR DESCRIPTION
**Pull request by neachdainn**
Closes #23 

The `publish_raw` method is not the most efficient since it allocates two vectors. But this works and it can be improved later without changing the interface.

### CODE REVIEW

**Comment by neachdainn** [comment]
This implementation is kind of backwards right now. Rather than converting the raw bytes into a message and sending that to the provider, the `Lcm` object should convert messages into raw bytes. Some time in the future (perhaps when the File provider is being added?) we should make the switch. Until then, I just want an interface available so I can duplicate the C LCM testing code.

**Comment by neachdainn** [comment]
I am now questioning why I split it into hash and bytes. I think I might fix that *and* fix the issue mentioned in the last comment before I really want this merged.

**Comment by neachdainn** [comment]
I think this is ready to merge. I'll make the fixes to UDPM and `Lcm` struct once I have the tests up and running.

**Comment by adeschamps** [comment]
Looks good. Thanks!

**Pull request merged**
